name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: make
      run: gcc -o hello main.c
    - uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: hello

    - uses: actions/download-artifact@v3
      with:
       name: my-artifact
       path: hello
